name: PR Test
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ] # master branch에 PR을 보낼 때 실행
 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
 
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
 
      # Gradle wrapper 파일 실행 권한주기
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
 
      # Gradle test를 실행한다
      - name: Test with Gradle
        run: ./gradlew --info test
        
      # 테스트 후 결과를 보기 위해 Publish Unit Test Result Step 추가
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: ${{ always() }}  # 테스트가 실패하여도 Report를 보기 위해 `always`로 설정
        with:
          files: build/test-results/**/*.xml
